#!/bin/sh

targetFps=10000
robloxPath="/Applications/Roblox.app"

if [ ! -d "$robloxPath" ]; then
  robloxPath="$HOME/Applications/Roblox.app"
  
  if [ ! -d "$robloxPath" ]; then
    echo "❌ Could Not Find Your Roblox, make sure it is installed."
    exit 1
  fi
fi

clientSettingsPath="$robloxPath/Contents/MacOS/ClientSettings"
mkdir -p "$clientSettingsPath"

clear
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎮  ROBLOX FPS BOOSTER"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔥 Choose your Graphics Mode:"
echo "1️⃣ Vulkan  (🚀 Most of your FPS, might break extra monitors)"
echo "2️⃣ Metal   (✔️ Best for most Macs)"
echo "3️⃣ OpenGL  (🖥️ Good for older Macs)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
read -r rendererChoice

disableMetal="false"
preferVulkan="false"
preferOpenGL="false"

case "$rendererChoice" in
  1) disableMetal="true"; preferVulkan="true";;
  2) disableMetal="false";;
  3) disableMetal="true"; preferOpenGL="true";;
  *) echo "❌ Wrong Choice, going back to metal as default."; disableMetal="false";;
esac

clear
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "⚡ Wanna go TURBO MODE? (yes/no)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
read -r performanceMode

graphicsTweaks=""
if [ "$performanceMode" = "yes" ] || [ "$performanceMode" = "y" ]; then
  graphicsTweaks='
      "FFlagRenderHighlightFXAA": "false",
      "FFlagDebugGraphicsDisableShadows": "true",
      "FFlagDebugGraphicsDisablePBR": "true",
      "FFlagDebugGraphicsDisableWaterReflection": "true",
      "DFFlagGraphicsTextureStreaming": "false",
      "DFIntTaskSchedulerBackgroundPriority": 3,
      "DFIntTaskSchedulerEnableJobThreads": "true",
      "DFIntTaskSchedulerNumThreads": 6,
  '
fi

clientSettings="{
  \"DFIntTaskSchedulerTargetFps\": $targetFps,
  \"FFlagDebugGraphicsDisableMetal\": \"$disableMetal\",
  \"FFlagDebugGraphicsPreferVulkan\": \"$preferVulkan\",
  \"FFlagDebugGraphicsPreferOpenGL\": \"$preferOpenGL\",
  $graphicsTweaks
}"

echo "$clientSettings" > "$clientSettingsPath/ClientAppSettings.json"

clear
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ FPS UNCAPPED AND BOOSTED SUB TO WREALAERO! 🎮"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
